/*
@TargetNode='localhost'
@GeneratedBy=migreene
@GenerationDate=12/08/2014 17:05:11
@GenerationHost=GREENEX1
*/

instance of  as $1ref
{
ResourceID = "[]MSDN";
 Ensure = "Present";
 AzurePublishSettingsFile = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\MSDN.publishsettings";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::46::9::";
 AzureSubscriptionName = "Visual Studio Ultimate with MSDN";
 ModuleName = "msAzure";
 ModuleVersion = "0.1.3";

 ConfigurationName = "CreateAzureTestVMs";

};
instance of  as $1ref
{
ResourceID = "[]TestVMAffinity";
 Description = "Affinity Group for Test Virtual Machines";
 Location = "West US";
 Ensure = "Present";
 Label = "TestVMWestUS2783158150";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::52::9::";
 Name = "TestVMWestUS2783158150";
 ModuleName = "msAzure";
 ModuleVersion = "0.1.3";

DependsOn = {

    "[]MSDN"};

 ConfigurationName = "CreateAzureTestVMs";

};
instance of MSFT_ as $MSFT_1ref
{
ResourceID = "[]TestVMStorage";
 Container = NULL;
 StorageAccountName = "testvmstorage2783158150";
 Ensure = "Present";
 Label = "testvmstorage2783158150";
 AffinityGroup = "TestVMWestUS2783158150";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::61::9::";
 ModuleName = "msAzure";
 ModuleVersion = "0.1.3";

DependsOn = {

    "[]TestVMAffinity"};

 ConfigurationName = "CreateAzureTestVMs";

};
instance of  as $1ref
{
ResourceID = "[]TestVMService";
 ServiceName = "testvmservice2783158150";
 Ensure = "Present";
 Label = "testvmservice2783158150";
 Description = "Service created for Test Virtual Machines";
 AffinityGroup = "TestVMWestUS2783158150";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::70::9::";
 ModuleName = "msAzure";
 ModuleVersion = "0.1.3";

DependsOn = {

    "[]TestVMStorage"};

 ConfigurationName = "CreateAzureTestVMs";

};
instance of DscConfiguration as $DscConfiguration1ref
{
ResourceID = "[DscConfiguration]ServerCoreFiles";
 StorageAccountName = "testvmstorage2783158150";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::80::9::DscConfiguration";
 ModuleName = "msAzure";
 ConfigurationPath = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\ServerCoreTest\\ServerCoreTest.ps1";
 ModuleVersion = "0.1.3";

 ConfigurationName = "CreateAzureTestVMs";

};
instance of MSFT_Credential as $MSFT_Credential1ref
{
Password = "Toyboat5";
 UserName = "mgadmin";

};

instance of  as $1ref
{
ResourceID = "[]TestVM1";
 ServiceName = "testvmservice2783158150";
 StorageAccountName = "testvmstorage2783158150";
 Credential = $MSFT_Credential1ref;
 Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::86::9::";
 Name = "TestVM1";
 Windows = True;
 ModuleName = "msAzure";
 ImageName = "a699494373c04fc0bc8f2bb1389d6106__Windows-Server-2012-R2-201411.01-en.us-127GB.vhd";
 ModuleVersion = "0.1.3";
 InstanceSize = "Medium";

DependsOn = {

    "[]TestVMService"};

 ConfigurationName = "CreateAzureTestVMs";

};
instance of DscExtension as $DscExtension1ref
{
ResourceID = "[DscExtension]ServerCoreDSCTest";
 ServiceName = "testvmservice2783158150";
 StorageAccountName = "testvmstorage2783158150";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\Modules\\msAzure\\Examples\\CreateWithDSCExtension.ps1::99::9::DscExtension";
 VMName = "TestVM1";
 ModuleName = "msAzure";
 Configuration = "ServerCoreTest";
 ConfigurationArchive = "ServerCoreTest.ps1.zip";
 ModuleVersion = "0.1.3";

 ConfigurationName = "CreateAzureTestVMs";

};
instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="migreene";
 GenerationDate="12/08/2014 17:05:11";
 GenerationHost="GREENEX1";
 Name="CreateAzureTestVMs";
};
